/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FigmaIcons
///      fonts:
///       - asset: fonts/FigmaIcons.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
library;
import 'package:flutter/widgets.dart';

class FigmaIcons {
  FigmaIcons._();

  static const _kFontFam = 'FigmaIcons';
  static const String? _kFontPkg = null;

  static const IconData calendar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customLogout = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teacher = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
